name: Trigger CAST from Kibana dashboard

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test type"
        required: false
        type: string
        default: ""
  repository_dispatch:
    types: [ trigger-from-pqd-cast ]

jobs:
  trigger-from-kibana-dashboard:
    name: Verify trigger from Kibana dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        if: inputs.test_type == 'Prod US Market Tests'
        run: echo "Prod US Market Tests!"

      - name: Run a multi-line script
        run: |
          echo ${{ github.event.client_payload.test_type }}
