name: Change report name

on:
  workflow_dispatch:

jobs:
  change-report-name:
    name: Change report name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        id: report
        run: |
          touch file.txt
          mkdir Report
          realpath Report
          zip -r report.zip file.txt
          mv file.txt ./Report
          zip_path=$(realpath report.zip)
          report_path=$(realpath Report)
          output="[{\"testKey\": \"Joynr\", \"status\": \"PASS\"},{\"testKey\": \"update with SMS\", \"status\": \"FAIL\"},{\"testKey\": \"SMS gateway\", \"status\": \"PASS\"}]"
          echo "$zip_path"
          echo "$report_path"
          echo "report_path=$report_path" >> $GITHUB_OUTPUT
          echo "results=$output" >> $GITHUB_OUTPUT

      - name: Add test results to summary
        if: always()
        run: |
          echo "### Test Results for run id ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "| Test Name | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          #echo '${{ steps.report.outputs.results }}' | jq
          #echo '${{ steps.report.outputs.results }}' | jq -r ' .[] | "| \(.testKey) | \(.status) |"' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.report.outputs.results }}' | jq -r ' .[] | "| \(.testKey) | \(.status) |"' | sed 's/PASS/✅ PASS/' | sed 's/FAIL/❌ FAIL/' >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
      
      - name: Upload Report as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: report-run-${{ github.run_id }}
          path: ${{ steps.report.outputs.report_path }}
